// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOutxB8PLl8T3y4-vpBp5zdDgPaq8allk',
    appId: '1:621067507703:web:19a5b36557c748374200f2',
    messagingSenderId: '621067507703',
    projectId: 'devignite-5823b',
    authDomain: 'devignite-5823b.firebaseapp.com',
    databaseURL: 'https://devignite-5823b-default-rtdb.firebaseio.com',
    storageBucket: 'devignite-5823b.appspot.com',
    measurementId: 'G-T3Q633BJZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg8Y8aGSvBJj0xTk8TILvUrrxXge_zy3M',
    appId: '1:621067507703:android:681842c659023f044200f2',
    messagingSenderId: '621067507703',
    projectId: 'devignite-5823b',
    databaseURL: 'https://devignite-5823b-default-rtdb.firebaseio.com',
    storageBucket: 'devignite-5823b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvwkw0h9cfU0Q4lJmOFK9Cys0EgLnr80',
    appId: '1:621067507703:ios:3195f7c5152c2ded4200f2',
    messagingSenderId: '621067507703',
    projectId: 'devignite-5823b',
    databaseURL: 'https://devignite-5823b-default-rtdb.firebaseio.com',
    storageBucket: 'devignite-5823b.appspot.com',
    iosClientId: '621067507703-1v2cvq5dsog2iqlqle17vbbc310o7upo.apps.googleusercontent.com',
    iosBundleId: 'com.example.evSimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvwkw0h9cfU0Q4lJmOFK9Cys0EgLnr80',
    appId: '1:621067507703:ios:bb994bb1e640e3ef4200f2',
    messagingSenderId: '621067507703',
    projectId: 'devignite-5823b',
    databaseURL: 'https://devignite-5823b-default-rtdb.firebaseio.com',
    storageBucket: 'devignite-5823b.appspot.com',
    iosClientId: '621067507703-gml99l2dh62nbufvcm29q19q5mok29gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.evSimulator.RunnerTests',
  );
}
